const sampleEmailBody = {
    emails: [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique neque velit. Quisque eleifend  viverra pretium. Maecenas id malesuada nisi. Curabitur venenatis ullamcorper nibh et molestie. Aliquam feugiat et lectus at lobortis. Praesent hendrerit dui non tempor commodo. Mauris hendrerit porta nisi sit amet lobortis. Vestibulum auctor et dui vitae consectetur. Vestibulum in mollis dolor. Fusce convallis libero leo, in venenatis est hendrerit sed. ",
        "Suspendisse tincidunt dignissim ipsum, vel tincidunt felis luctus eu. Praesent congue vitae ante aliquet viverra. Praesent venenatis nulla vel ex laoreet tempor. In tincidunt sem nibh. Etiam dictum sem massa, vel tincidunt enim tincidunt quis. Sed eu massa accumsan, ultricies lectus eget, interdum dui. Vivamus urna libero, ullamcorper vel magna nec, condimentum maximus urna. Nullam fringilla purus ac nulla gravida, et sagittis massa sagittis. Nam tempor felis erat, sed congue urna condimentum vitae. Integer finibus varius faucibus. Proin ultrices scelerisque leo, quis ultricies urna vulputate sed. Nam consequat erat a pharetra tempus. ",
        "Sed non bibendum augue. Suspendisse eu lectus augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut non tortor venenatis, auctor leo ut, tincidunt ligula. Vestibulum aliquet nibh vel quam venenatis, at porta sem placerat. Proin tempus arcu sodales nibh scelerisque posuere. Etiam in rhoncus mi. Morbi venenatis ante eu tincidunt dignissim. Suspendisse congue mi non blandit molestie. Quisque lectus ipsum, tincidunt id massa eu, dictum viverra leo. ",
        "Maecenas porta suscipit est ac suscipit. Nulla facilisi. Phasellus eu gravida justo. Ut eget neque fermentum, fringilla libero sed, fermentum elit. Nullam et velit id lorem posuere sollicitudin eget sit amet libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent tempus efficitur diam non congue. In porta molestie massa, vitae vestibulum lectus pharetra et. Duis sit amet ultricies lectus, et fermentum massa. Phasellus in odio hendrerit, interdum turpis eu, auctor odio. Etiam tincidunt semper lorem, in placerat velit tristique eget. Vestibulum sit amet ex egestas metus scelerisque ultrices. ",
        "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc bibendum erat ac enim fringilla, eget gravida est commodo. Morbi pharetra hendrerit nulla sed sagittis. Aenean ex nisl, euismod et lacus non, lacinia tincidunt velit. Ut sit amet sollicitudin nisl. Etiam dignissim odio vitae mauris ultrices finibus vitae eu quam. Aenean pellentesque est et nunc hendrerit, quis accumsan velit luctus. In sed ante eu elit vulputate blandit. Aliquam augue ligula, molestie nec mollis ac, vehicula sed risus. Morbi sapien ante, consequat in suscipit at, maximus at sem. Suspendisse ultricies nisl in erat aliquam iaculis. Donec faucibus lacus sit amet justo euismod vehicula. Duis eu enim sit amet tortor viverra feugiat. ",
        "Taco bell chihuahua alternative rock choker necklace toyota supra, britpop uncle phil pearl jam sugar ray videocassette toni braxton. The simpsons keanu reeves madonna west wing. Encarta sega genesis dallas cowboys pogs toyota previa. Bubble tape atlanta braves starter jackets butterfly clips turquoise, boyz II men bike caps pop punk destiny’s child tamagotchi punk.",
        "Choker necklace jeans dj jazzy jeff got milk yin yang scrunched socks. Skip it sideburns digital pets clueless alta vista, chia pet joey tribbiani valley girl keanu reeves flip flops madonna. Highlights lion king pagers chuck taylor all-stars, maze screensavers playa overalls with one strap undone apollo 13 oregon trail. Sup overalls the matrix wearing your cap backwards, puff daddy super nintendo personalized mixtapes sugar ray.",
        "Jagged little pill screening phone calls your mom skip it roseanne barr pizza bagels. Tupac shakur bowl cut catsuit good will hunting. Rush hour coral adidas aerosmith barbie, leggings smashing pumpkins royal stewart tartan wearing your cap backwards new kids on the block super nintendo. Warheads blur hush puppies tootsie pop dallas cowboys. Roseanne yo-yos rad zack morris. Hotmail kool-aid man snoop dogg britpop bucket hats snapple.",
        "Converse aerosmith snapple stonewashed blue jeans, headbands acid wash renting movies at a store how do you like them apples. Wayne’s world beepers flannel shirts braveheart coral, fila frasier accent braids can’t touch this. Dolly the sheep this is your brain on drugs the rachel haircut overalls. Space jam airwalk bill gates sega genesis cutoff jeans marky mark, nerf guns sonic the hedgehog eminem turquoise independence day.",
        "Lisa frank the mighty ducks the phantom menace turquoise sideburns babyface. Wayne gretzky wesley snipes denzel washington boyz II men, street fighter ii inflatable furniture garth brooks patti mayonnaise taco bell chihuahua trainers. Butterfly clips forrest gump millenials this is your brain on drugs. Discman koosh ball playa george foreman grill members only jackets home skillet, home improvement turtlenecks the matrix overalls schindler’s list. Apollo 13 parting your hair down the middle fanny packs I will always love you toyota previa track jackets."
    ]
};
export default sampleEmailBody;